version: '3.1'

services:
  db:
    image: library/mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: nopassword
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: mactronique/cua-server:latest
    ports:
      - "9500:80"
    depends_on:
      - db

